### ISSUE TITLE
 Failed to decrypt with DPAPI

### ISSUE THREAD

**Issue by yidi000** [vgvr0/TikTok-Video-Downloader-using-Python-and-yt-dlp#1]
[TikTok] Extracting URL: https://www.tiktok.com/@houseofmemesssss/video/7434055688768212255
[TikTok] 7434055688768212255: Downloading webpage
Extracting cookies from chrome
ERROR: Failed to decrypt with DPAPI. See  https://github.com/yt-dlp/yt-dlp/issues/10927  for more info
ERROR: ERROR: Failed to decrypt with DPAPI. See  https://github.com/yt-dlp/yt-dlp/issues/10927  for more info
Error downloading video: ERROR: ERROR: Failed to decrypt with DPAPI. See  https://github.com/yt-dlp/yt-dlp/issues/10927  for more info

The error is like above. I checked the link it provided but I still can't get it. Anyone can help with this problem? I am new to this.

**Comment by vgvr0** [comment]
Thanks for the sight. What version of the libraries do you have?

**Comment by yidi000** [comment]
> Thanks for the sight. What version of the libraries do you have?

where can I find the version of libraries? you mean the yt-dlp version? it is 2024.11.4. thx

**Comment by vgvr0** [comment]
I am currently using yt-dlp version 2024.10.7 and will try updating to the latest version to see if it resolves the issue.

**Comment by yidi000** [comment]
> I am currently using yt-dlp version 2024.10.7 and will try updating to the latest version to see if it resolves the issue.

Thanks. Should I try to install 2024.10.7 version?

**Comment by vgvr0** [comment]
Have you been able to run it with this version?

**Comment by Dreamscape-419** [comment]
I am also getting this error. Is there a fix for this?

**Comment by mrafieefard** [comment]
I think I found it just need to remove cookiesfrombrowser param from ydl_opts
